command: ["uvicorn", "app:app", "--app-dir", "backend"]
env:
  - name: 'MODE'
    value: 'DBX'
  - name: 'DATABRICKS_HOST'
    value: 'https://adb-2205520462893510.10.azuredatabricks.net'
  - name: 'WORKSPACE_ID'
    value: '2205520462893510'
  - name: 'LAKEBASE_HOST'
    value: 'instance-63a34be9-e2c7-439c-b2f6-f738d649e520.database.azuredatabricks.net'
  - name: 'LAKEBASE_PORT'
    value: '5432'
  - name: 'LAKEBASE_DATABASE'
    value: 'databricks_postgres'
  - name: 'LAKEBASE_USER'
    value: 'sbfi_admin'
  - name: 'LAKEBASE_PASSWORD'
    value: 'DBX@Lakebase+sbfi@2025'
